name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: pytest tests\test_api.py

  # build-and-deploy:
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Build and push Docker image
  #     run: |
  #       docker build . -t ${{ secrets.DOCKER_USERNAME }}/my-repo-name:latest
  #       docker push ${{ secrets.DOCKER_USERNAME }}/my-repo-name:latest

  #   - name: Deploy to server
  #     run: |
  #       # Your deployment commands go here
  #       echo "Deploying application..."
